In [1]:
import numpy as np
import pickle

In [10]:
# files
## realdata
test_realdata_images_r1 = np.load('rank_output_test_repeat/images_test_realdata_round_1/900_780_matches.npz')
test_realdata_images_r2 = np.load('rank_output_test_repeat/images_test_realdata_round_2/900_780_matches.npz')
test_realdata_images_r3 = np.load('rank_output_test_repeat/images_test_realdata_round_3/900_780_matches.npz')

test_realdata_superpoints_r1 = np.load('rank_output_test_repeat/superpoints_test_realdata_round_1/900_780_matches.npz')
test_realdata_superpoints_r2 = np.load('rank_output_test_repeat/superpoints_test_realdata_round_2/900_780_matches.npz')
test_realdata_superpoints_r3 = np.load('rank_output_test_repeat/superpoints_test_realdata_round_3/900_780_matches.npz')

## realdata_2
test_realdata2_images_r1 = np.load('rank_output_test_repeat/images_test_realdata2_round_1/120_240_matches.npz')
test_realdata2_images_r2 = np.load('rank_output_test_repeat/images_test_realdata2_round_2/120_240_matches.npz')
test_realdata2_images_r3 = np.load('rank_output_test_repeat/images_test_realdata2_round_3/120_240_matches.npz')

test_realdata2_superpoints_r1 = np.load('rank_output_test_repeat/superpoints_test_realdata2_round_1/120_240_matches.npz')
test_realdata2_superpoints_r2 = np.load('rank_output_test_repeat/superpoints_test_realdata2_round_2/120_240_matches.npz')
test_realdata2_superpoints_r3 = np.load('rank_output_test_repeat/superpoints_test_realdata2_round_3/120_240_matches.npz')

## new superpoints
new_test_realdata_superpoints_r1 = np.load('rank_output_test_repeat/new_superpoints_test_realdata_round_1/900_780_matches.npz')
new_test_realdata_superpoints_r2 = np.load('rank_output_test_repeat/new_superpoints_test_realdata_round_2/900_780_matches.npz')
new_test_realdata_superpoints_r3 = np.load('rank_output_test_repeat/new_superpoints_test_realdata_round_3/900_780_matches.npz')

new_test_realdata2_superpoints_r1 = np.load('rank_output_test_repeat/new_superpoints_test_realdata2_round_1/120_240_matches.npz')
new_test_realdata2_superpoints_r2 = np.load('rank_output_test_repeat/new_superpoints_test_realdata2_round_2/120_240_matches.npz')
new_test_realdata2_superpoints_r3 = np.load('rank_output_test_repeat/new_superpoints_test_realdata2_round_3/120_240_matches.npz')

# Compare keypoints

In [11]:
with open('saved_superpoints/pickle/test_realdata/900.pickle', 'rb') as file:
    test_superpoints_kp = pickle.load(file)

In [12]:
with open('saved_superpoints/pickle/test_realdata_new_code/900.pickle', 'rb') as file:
    test_superpoints_new_code_kp = pickle.load(file)

In [13]:
test_superpoints_kp['keypoints'][0].shape

torch.Size([480, 2])

In [14]:
test_realdata_superpoints_r1['keypoints0'].shape

(480, 2)

In [15]:
test_superpoints_kp['keypoints'][0]

tensor([[113.,   8.],
        [128.,   8.],
        [208.,   8.],
        [ 85.,   9.],
        [188.,   9.],
        [ 93.,  10.],
        [138.,  10.],
        [147.,  10.],
        [160.,  10.],
        [168.,  10.],
        [178.,  10.],
        [193.,  10.],
        [237.,  10.],
        [294.,  10.],
        [217.,  11.],
        [273.,  11.],
        [ 73.,  14.],
        [120.,  14.],
        [ 94.,  15.],
        [256.,  15.],
        [ 63.,  16.],
        [303.,  16.],
        [191.,  17.],
        [226.,  17.],
        [293.,  17.],
        [130.,  18.],
        [139.,  18.],
        [146.,  18.],
        [173.,  18.],
        [182.,  18.],
        [199.,  18.],
        [ 29.,  19.],
        [ 74.,  19.],
        [160.,  19.],
        [237.,  19.],
        [ 64.,  21.],
        [ 94.,  21.],
        [293.,  22.],
        [139.,  23.],
        [208.,  23.],
        [160.,  25.],
        [217.,  25.],
        [228.,  25.],
        [ 94.,  26.],
        [121.,  26.],
        [1

In [16]:
np.sum(test_superpoints_kp['keypoints'][0].cpu().numpy() != test_realdata_superpoints_r1['keypoints0'])

0

In [17]:
test_realdata_superpoints_r1.files

['keypoints0', 'keypoints1', 'matches', 'match_confidence']

In [18]:
test_realdata_superpoints_r1['keypoints0'].shape

(480, 2)

In [19]:
test_realdata_images_r1['keypoints0'].shape

(473, 2)

In [20]:
np.sum(test_realdata_superpoints_r1['keypoints0'][:-7,:] != test_realdata_images_r1['keypoints0'])

671

## New code

In [21]:
test_superpoints_new_code_kp['keypoints'][0].cpu().numpy().shape

(473, 2)

In [22]:
np.sum(test_superpoints_new_code_kp['keypoints'][0].cpu().numpy() != test_realdata_images_r1['keypoints0'])

0

# Compare matching from loaded files above

In [23]:
test_realdata_images_r1.files

['keypoints0', 'keypoints1', 'matches', 'match_confidence']

In [24]:
test_realdata_images_r1['matches']

array([  4,  -1,  -1,   6,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,   8,  12,  11,  -1,  -1,  -1,  -1,  -1,  -1,  13,
        -1,  -1,  -1,  -1,  -1,  27,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  25,  24,  -1,  -1,  -1,  41,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  26,  -1,  -1,  -1,  -1,  38,  60,
        45,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  44,  -1,  -1,  59,  54,  -1,  62,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  57,  65,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        74,  -1,  -1,  78,  72,  75,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        80,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        89,  92,  -1,  -1,  -1,  -1,  -1,  -1, 106, 103,  -1, 102,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -

In [25]:
print('Real data 1 from Images')
print('r1 vs r2 difference:',np.sum(test_realdata_images_r1['matches'] != test_realdata_images_r2['matches']))
print('r1 vs r3 difference:',np.sum(test_realdata_images_r1['matches'] != test_realdata_images_r3['matches']))
print('r2 vs r3 difference:',np.sum(test_realdata_images_r2['matches'] != test_realdata_images_r3['matches']))

Real data 1 from Images
r1 vs r2 difference: 0
r1 vs r3 difference: 0
r2 vs r3 difference: 0


In [26]:
print('Real data 1 from SuperPoints')
print('r1 vs r2 difference:',np.sum(test_realdata_superpoints_r1['matches'] != test_realdata_superpoints_r2['matches']))
print('r1 vs r3 difference:',np.sum(test_realdata_superpoints_r1['matches'] != test_realdata_superpoints_r3['matches']))
print('r2 vs r3 difference:',np.sum(test_realdata_superpoints_r2['matches'] != test_realdata_superpoints_r3['matches']))

Real data 1 from SuperPoints
r1 vs r2 difference: 0
r1 vs r3 difference: 0
r2 vs r3 difference: 0


In [27]:
print('Real data 2 from Images')
print('r1 vs r2 difference:',np.sum(test_realdata2_images_r1['matches'] != test_realdata2_images_r2['matches']))
print('r1 vs r3 difference:',np.sum(test_realdata2_images_r1['matches'] != test_realdata2_images_r3['matches']))
print('r2 vs r3 difference:',np.sum(test_realdata2_images_r2['matches'] != test_realdata2_images_r3['matches']))

Real data 2 from Images
r1 vs r2 difference: 0
r1 vs r3 difference: 0
r2 vs r3 difference: 0


In [28]:
print('Real data 2 from SuperPoints')
print('r1 vs r2 difference:',np.sum(test_realdata2_superpoints_r1['matches'] != test_realdata2_superpoints_r2['matches']))
print('r1 vs r3 difference:',np.sum(test_realdata2_superpoints_r1['matches'] != test_realdata2_superpoints_r3['matches']))
print('r2 vs r3 difference:',np.sum(test_realdata2_superpoints_r2['matches'] != test_realdata2_superpoints_r3['matches']))

Real data 2 from SuperPoints
r1 vs r2 difference: 0
r1 vs r3 difference: 0
r2 vs r3 difference: 0


In [29]:
print('Real data 1 Images vs SuperPoints')
print('R1: Images vs SuperPoints difference:',np.sum(test_realdata_images_r1['matches'] != test_realdata_superpoints_r1['matches']))
print('R2: Images vs SuperPoints difference:',np.sum(test_realdata_images_r2['matches'] != test_realdata_superpoints_r2['matches']))
print('R3: Images vs SuperPoints difference:',np.sum(test_realdata_images_r3['matches'] != test_realdata_superpoints_r3['matches']))

Real data 1 Images vs SuperPoints
R1: Images vs SuperPoints difference: 1
R2: Images vs SuperPoints difference: 1
R3: Images vs SuperPoints difference: 1


<ipython-input-29-b04f1b4833fe>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('R1: Images vs SuperPoints difference:',np.sum(test_realdata_images_r1['matches'] != test_realdata_superpoints_r1['matches']))
<ipython-input-29-b04f1b4833fe>:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('R2: Images vs SuperPoints difference:',np.sum(test_realdata_images_r2['matches'] != test_realdata_superpoints_r2['matches']))
<ipython-input-29-b04f1b4833fe>:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('R3: Images vs SuperPoints difference:',np.sum(test_realdata_images_r3['matches'] != test_realdata_superpoints_r3['matches']))


In [30]:
test_realdata_images_r1['matches'].shape

(473,)

In [31]:
test_realdata_superpoints_r1['matches'].shape

(480,)

In [32]:
print('Real data 1 Images vs SuperPoints')
print('R1: Images vs SuperPoints difference:',np.sum(test_realdata_images_r1['matches'] != test_realdata_superpoints_r1['matches'][:-7]))
print('R2: Images vs SuperPoints difference:',np.sum(test_realdata_images_r2['matches'] != test_realdata_superpoints_r2['matches'][:-7]))
print('R3: Images vs SuperPoints difference:',np.sum(test_realdata_images_r3['matches'] != test_realdata_superpoints_r3['matches'][:-7]))

Real data 1 Images vs SuperPoints
R1: Images vs SuperPoints difference: 188
R2: Images vs SuperPoints difference: 188
R3: Images vs SuperPoints difference: 188


In [33]:
test_realdata2_images_r1['matches'].shape

(303,)

In [34]:
test_realdata2_superpoints_r1['matches'].shape

(299,)

In [35]:
print('Real data 2 Images vs SuperPoints')
print('R1: Images vs SuperPoints difference:',np.sum(test_realdata2_images_r1['matches'][:-4] != test_realdata2_superpoints_r1['matches']))
print('R2: Images vs SuperPoints difference:',np.sum(test_realdata2_images_r2['matches'][:-4] != test_realdata2_superpoints_r2['matches']))
print('R3: Images vs SuperPoints difference:',np.sum(test_realdata2_images_r3['matches'][:-4] != test_realdata2_superpoints_r3['matches']))

Real data 2 Images vs SuperPoints
R1: Images vs SuperPoints difference: 246
R2: Images vs SuperPoints difference: 246
R3: Images vs SuperPoints difference: 246


In [36]:
print('Real data 1 new_SuperPoints vs SuperPoints')
print('R1: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata_superpoints_r1['matches'] != test_realdata_superpoints_r1['matches']))
print('R2: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata_superpoints_r2['matches'] != test_realdata_superpoints_r2['matches']))
print('R3: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata_superpoints_r3['matches'] != test_realdata_superpoints_r3['matches']))

Real data 1 new_SuperPoints vs SuperPoints
R1: new_SuperPoints vs SuperPoints difference: 0
R2: new_SuperPoints vs SuperPoints difference: 0
R3: new_SuperPoints vs SuperPoints difference: 0


In [37]:
print('Real data 2 new_SuperPoints vs SuperPoints')
print('R1: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata2_superpoints_r1['matches'] != test_realdata2_superpoints_r1['matches']))
print('R2: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata2_superpoints_r2['matches'] != test_realdata2_superpoints_r2['matches']))
print('R3: new_SuperPoints vs SuperPoints difference:',np.sum(new_test_realdata2_superpoints_r3['matches'] != test_realdata2_superpoints_r3['matches']))

Real data 2 new_SuperPoints vs SuperPoints
R1: new_SuperPoints vs SuperPoints difference: 0
R2: new_SuperPoints vs SuperPoints difference: 0
R3: new_SuperPoints vs SuperPoints difference: 0


In [38]:
test_realdata_images_r1['matches']

array([  4,  -1,  -1,   6,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,   8,  12,  11,  -1,  -1,  -1,  -1,  -1,  -1,  13,
        -1,  -1,  -1,  -1,  -1,  27,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  25,  24,  -1,  -1,  -1,  41,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  26,  -1,  -1,  -1,  -1,  38,  60,
        45,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  44,  -1,  -1,  59,  54,  -1,  62,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  57,  65,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        74,  -1,  -1,  78,  72,  75,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        80,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        89,  92,  -1,  -1,  -1,  -1,  -1,  -1, 106, 103,  -1, 102,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -

In [39]:
test_realdata_superpoints_r1['matches']

array([  4,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,   7,  11,  10,  -1,  -1,  -1,  -1,  -1,  -1,  12,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  19,  -1,  -1,
        -1,  -1,  -1,  -1,  25,  24,  -1,  -1,  -1,  40,  -1,  -1,  -1,
        -1,  -1,  -1,  30,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  26,  -1,  -1,  -1,  -1,  -1,  -1,  37,  58,  44,  -1,
        -1,  50,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  -1,  43,  -1,  -1,  57,  52,  -1,  59,  -1,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  61,  -1,  -1,  -1,
        -1,  -1,  -1,  -1,  -1,  65,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        -1,  72,  -1,  -1,  75,  70,  -1,  -1,  -1,  -1,  81,  -1,  -1,
        -1,  -1,  83,  -1,  -1,  -1,  -1,  -1,  -1,  77,  -1,  -1,  -1,
        -1,  -1,  91,  89,  -1,  -1,  -1,  -1,  -1, 105, 101,  -1, 100,
        -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -

In [40]:
test_realdata_images_new = np.load('rank_output/rank_output_realdata_for_visual/900_0_matches.npz')
test_realdata_superpoints_new_code = np.load('rank_output/rank_output_test_realdata_superpoints_new_code/900_0_matches.npz')

In [41]:
test_realdata_images_new.files

['keypoints0', 'keypoints1', 'matches', 'match_confidence']

In [42]:
test_realdata_images_new['keypoints0'].shape

(473, 2)

In [43]:
test_realdata_superpoints_new_code['keypoints0'].shape

(473, 2)

In [44]:
np.sum(test_realdata_images_new['keypoints0'] != test_realdata_superpoints_new_code['keypoints0'])

0

In [45]:
np.sum(test_realdata_images_new['keypoints1'] != test_realdata_superpoints_new_code['keypoints1'])

0

In [46]:
np.sum(test_realdata_images_new['matches'] != test_realdata_superpoints_new_code['matches'])

0

In [47]:
np.sum(test_realdata_images_new['match_confidence'] != test_realdata_superpoints_new_code['match_confidence'])

120

In [56]:
test_realdata_images_new['match_confidence'][:100]

array([0.        , 0.02859623, 0.        , 0.        , 0.21447068,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0929807 , 0.        , 0.        , 0.        , 0.07175788,
       0.        , 0.        , 0.        , 0.        , 0.08293964,
       0.        , 0.        , 0.25893846, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.23003113, 0.07671124,
       0.        , 0.        , 0.        , 0.        , 0.14450963,
       0.        , 0.        , 0.        , 0.15228118, 0.        ,
       0.        , 0.51550406, 0.        , 0.        , 0.        ,
       0.14439294, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07407591, 0.        , 0.        , 0.06321839,
       0.1779422 , 0.        , 0.29777697, 0.        , 0.23977214,
       0.        , 0.11099059, 0.35815427, 0.        , 0.        ,
       0.        , 0.        , 0.4072664 , 0.        , 0.37102

In [57]:
test_realdata_superpoints_new_code['match_confidence'][:100]

array([0.        , 0.02859606, 0.        , 0.        , 0.21446905,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.09297981, 0.        , 0.        , 0.        , 0.07175733,
       0.        , 0.        , 0.        , 0.        , 0.08293932,
       0.        , 0.        , 0.25893822, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.23003092, 0.07671095,
       0.        , 0.        , 0.        , 0.        , 0.14451018,
       0.        , 0.        , 0.        , 0.15228218, 0.        ,
       0.        , 0.51552796, 0.        , 0.        , 0.        ,
       0.14439335, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07407683, 0.        , 0.        , 0.06321906,
       0.17794545, 0.        , 0.29779088, 0.        , 0.23977008,
       0.        , 0.11099164, 0.35819864, 0.        , 0.        ,
       0.        , 0.        , 0.40732348, 0.        , 0.37102

# Examine API results

In [9]:
# query here is 60.png
api_result_query_60 = np.load('api_output/query_60_matches.npz')

In [10]:
api_result_query_60.files

['keypoints0', 'keypoints1', 'matches', 'match_confidence']

In [11]:
api_result_query_60['keypoints0'].shape

(460, 2)

In [12]:
api_result_query_60['keypoints1'].shape

(460, 2)

In [13]:
# query here is 60.png
api_result_query_0 = np.load('api_output/query_0_matches.npz')

In [14]:
api_result_query_0['keypoints0'].shape

(460, 2)

In [15]:
api_result_query_0['keypoints1'].shape

(649, 2)